<a href="https://colab.research.google.com/github/oliveiradev06/dengue-brazil/blob/main/dengue_brazil.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import files
uploaded = files.upload()

Saving dataset.csv to dataset.csv

In [7]:
import pandas as pd

df = pd.read_csv("dataset.csv")
df.head()

,Gender,Age,NS1,IgG,IgM,Area,AreaType,HouseType,District,Outcome
0,Female,45,0,0,0,Mirpur,Undeveloped,Building,Dhaka,0
1,Male,17,0,0,1,Chawkbazar,Developed,Building,Dhaka,0
2,Female,29,0,0,0,Paltan,Undeveloped,Other,Dhaka,0
3,Female,63,1,1,0,Motijheel,Developed,Other,Dhaka,1
4,Male,22,0,0,0,Gendaria,Undeveloped,Building,Dhaka,0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Gender     1000 non-null   object
 1   Age        1000 non-null   int64
 2   NS1        1000 non-null   int64
 3   IgG        1000 non-null   int64
 4   IgM        1000 non-null   int64
 5   Area       1000 non-null   object
 6   AreaType   1000 non-null   object
 7   HouseType  1000 non-null   object
 8   District   1000 non-null   object
 9   Outcome    1000 non-null   int64
dtypes: int64(5), object(5)
memory usage: 78.3+ KB

In [14]:
linhas, colunas = df.shape[0],df.shape[1]
print("N° de Linhas:", linhas)
print("N° de Colunas:" , colunas)

N° de Linhas: 1000
N° de Colunas: 10

In [17]:
df.columns

Index(['Gender', 'Age', 'NS1', 'IgG', 'IgM', 'Area', 'AreaType', 'HouseType',
       'District', 'Outcome'],
      dtype='object')

In [20]:
df.rename(columns={
    'Gender' : 'Gênero',
    'Age' : 'Idade',
    'NS1' : 'NS1', #Resultado do teste NS1 (antígeno da dengue) – geralmente positivo nos primeiros dias da infecção.
    'IgG' : 'IgG', #Resultado do teste IgG (imunoglobulina G) – indica infecção passada ou mais prolongada.
    'IgM' : 'IgM', #Resultado do teste IgM (imunoglobulina M) – indica infecção recente/ativa.
    'Area' : 'Área',
    'AreaType' : 'Tipo de Área',#Se é urbana, rural, periurbana, etc.
    'District' : 'Distrito', #Região administrativa/município onde o paciente reside.
    'Outcome' : 'Desfecho' #Resultado final do caso (Recuperado, Internado, Óbito, etc.).


},inplace=True)

In [21]:
df.columns

Index(['Gênero', 'Idade', 'NS1', 'IgG', 'IgM', 'Área', 'Tipo de Área',
       'HouseType', 'Distrito', 'Desfecho'],
      dtype='object')

In [23]:
df.shape

(1000, 10)

In [24]:
df.head()

,Gênero,Idade,NS1,IgG,IgM,Área,Tipo de Área,HouseType,Distrito,Desfecho
0,Female,45,0,0,0,Mirpur,Undeveloped,Building,Dhaka,0
1,Male,17,0,0,1,Chawkbazar,Developed,Building,Dhaka,0
2,Female,29,0,0,0,Paltan,Undeveloped,Other,Dhaka,0
3,Female,63,1,1,0,Motijheel,Developed,Other,Dhaka,1
4,Male,22,0,0,0,Gendaria,Undeveloped,Building,Dhaka,0

In [25]:
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gênero        1000 non-null   object
 1   Idade         1000 non-null   int64
 2   NS1           1000 non-null   int64
 3   IgG           1000 non-null   int64
 4   IgM           1000 non-null   int64
 5   Área          1000 non-null   object
 6   Tipo de Área  1000 non-null   object
 7   HouseType     1000 non-null   object
 8   Distrito      1000 non-null   object
 9   Desfecho      1000 non-null   int64
dtypes: int64(5), object(5)
memory usage: 78.3+ KB

Gênero          0
Idade           0
NS1             0
IgG             0
IgM             0
Área            0
Tipo de Área    0
HouseType       0
Distrito        0
Desfecho        0
dtype: int64

In [26]:
df["Idade"].describe()

count    1000.000000
mean       35.924000
std        16.468437
min         8.000000
25%        22.000000
50%        37.000000
75%        50.000000
max        65.000000
Name: Idade, dtype: float64

In [35]:
df["Área"].value_counts()

Área
Demra                  38
Jatrabari              38
Mirpur                 34
Bangshal               34
Kadamtali              34
Dhanmondi              34
New Market             33
Keraniganj             33
Tejgaon                31
Badda                  31
Paltan                 31
Sutrapur               31
Biman Bandar           30
Rampura                30
Khilkhet               30
Ramna                  30
Banasree               29
Mohammadpur            28
Gulshan                28
Motijheel              27
Kalabagan              27
Kafrul                 26
Kamrangirchar          26
Hazaribagh             25
Shahbagh               24
Bosila                 24
Khilgaon               23
Sher-e-Bangla Nagar    23
Pallabi                23
Sabujbagh              23
Chawkbazar             22
Gendaria               22
Adabor                 22
Cantonment             20
Shyampur               19
Lalbagh                17
Name: count, dtype: int64

In [40]:
df['Área'] = df['Área'].replace ({
    "Demra": "Demra",
    "Jatrabari": "Jatrabari",
    "Mirpur": "Mirpur",
    "Bangshal": "Bangshal",
    "Kadamtali": "Kadamtali",
    "Dhanmondi": "Dhanmondi",
    "New Market": "Novo Mercado",
    "Keraniganj": "Keraniganj",
    "Tejgaon": "Tejgaon",
    "Badda": "Badda",
    "Paltan": "Paltan",
    "Sutrapur": "Sutrapur",
    "Biman Bandar": "Aeroporto",
    "Rampura": "Rampura",
    "Khilkhet": "Khilkhet",
    "Ramna": "Ramna",
    "Banasree": "Banasree",
    "Mohammadpur": "Mohammadpur",
    "Gulshan": "Gulshan",
    "Motijheel": "Motijheel",
    "Kalabagan": "Kalabagan",
    "Kafrul": "Kafrul",
    "Kamrangirchar": "Kamrangirchar",
    "Hazaribagh": "Hazaribagh",
    "Shahbagh": "Shahbagh",
    "Bosila": "Bosila",
    "Khilgaon": "Khilgaon",
    "Sher-e-Bangla Nagar": "Sher-e-Bangla Nagar",
    "Pallabi": "Pallabi",
    "Sabujbagh": "Sabujbagh",
    "Chawkbazar": "Chawkbazar",
    "Gendaria": "Gendaria",
    "Adabor": "Adabor",
    "Cantonment": "Quartel",
    "Shyampur": "Shyampur",
    "Lalbagh": "Lalbagh"
})

# Aplicar substituição
df["Área"].value_counts()

Área
<bound method NDFrame.replace of 0            Mirpur\n1        Chawkbazar\n2            Paltan\n3         Motijheel\n4          Gendaria\n           ...     \n995    Novo Mercado\n996          Paltan\n997       Motijheel\n998          Paltan\n999          Adabor\nName: Área, Length: 1000, dtype: object>    1000
Name: count, dtype: int64